/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hasanozgan.kafkabank.transactionproducer

import com.typesafe.config.Config
import com.winterbe.expekt.should
import io.mockk.every
import io.mockk.mockk
import org.junit.jupiter.api.Assertions.assertEquals
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe

class AppTest : Spek({
    val mockConfig: Config = mockk()

    beforeEachTest {
        println("abc de")
    }

    beforeGroup {
        println("xyz 1")
    }

    describe("a calculator") {
        beforeGroup {
            every { mockConfig.getString(any()) }
            every { mockConfig.getString(any()) }
        }

        it("should return the result of adding the first number to the second number") {

            "asd".should.be.equal("asd")
            3.2.should.be.closeTo(3.2, delta = 0.1)
        }

        describe("") {
            it("should return the result of subtracting the second number from the first number") {
                assertEquals("asd", "asd")
            }
        }
    }

    describe("asd") {
        it("asd") {
            "asdf".should.be.equal("asdf")
        }
    }

})
