/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hasanozgan.kafkabank.balanceaggregator

import com.hasanozgan.kafkabank.balanceaggregator.config.AppConfig
import com.hasanozgan.kafkabank.balanceaggregator.kafkaclient.KafkaConsumerClient
import com.hasanozgan.kafkabank.balanceaggregator.service.TransactionConsumer

fun main() {
    val appConfig = AppConfig()
    val kafkaProducerClient = KafkaConsumerClient(appConfig.applicationID,
            appConfig.bootstrapServers,
            appConfig.schemaRegistryUrl,
            appConfig.transactionTopicName,
            appConfig.balanceTopicName)

    TransactionConsumer(kafkaProducerClient).start();
}
