/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hasanozgan.kafkabank.transactionproducer

import com.hasanozgan.kafkabank.transactionproducer.config.AppConfig
import com.hasanozgan.kafkabank.transactionproducer.service.TransactionGenerator
import com.hasanozgan.kafkabank.transactionproducer.service.TransactionProducer
import com.hasanozgan.kafkabank.transactionproducer.service.TransactionSender
import io.github.serpro69.kfaker.Faker
import com.hasanozgan.kafkabank.transactionproducer.kafkaclient.KafkaProducerClient
import kotlinx.coroutines.*


@ObsoleteCoroutinesApi
fun main(args: Array<String>) = runBlocking<Unit> {

    Faker.init("en")
    val appConfig = AppConfig()

    val transactionGenerator = TransactionGenerator(appConfig.accountSize,
            appConfig.transactionLimitFrom,
            appConfig.transactionLimitUntil,
            appConfig.openingBalance)

    val kafkaProducerClient = KafkaProducerClient(appConfig.bootstrapServers,
            appConfig.schemaRegistryUrl,
            appConfig.topicName)

    val transactionSender = TransactionSender(kafkaProducerClient)

    TransactionProducer(transactionGenerator, transactionSender).produce()
}

